# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

self-hosted-runner:
  labels:
    - linux-amd64-cpu8
    - linux-amd64-gpu-rtxpro6000-latest-1
    - linux-arm64-cpu8
    - linux-arm64-gpu-l4-latest-1
    - nv
    - ubuntu-26.04
    - windows-arm64
    - wsl-amd64-gpu-rtxpro6000-latest-1

paths:
  .github/workflows/windows-msvc.yml:
    ignore:
      - 'constant expression "false" in condition'
