// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: datamodel.proto

package datamodelv1

import (
	_ "github.com/NVIDIA/OpenShell/sdk/go/proto/optionsv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Phase of a workspace's lifecycle.
type WorkspacePhase int32

const (
	WorkspacePhase_WORKSPACE_PHASE_UNSPECIFIED WorkspacePhase = 0
	WorkspacePhase_WORKSPACE_PHASE_ACTIVE      WorkspacePhase = 1
	WorkspacePhase_WORKSPACE_PHASE_TERMINATING WorkspacePhase = 2
)

// Enum value maps for WorkspacePhase.
var (
	WorkspacePhase_name = map[int32]string{
		0: "WORKSPACE_PHASE_UNSPECIFIED",
		1: "WORKSPACE_PHASE_ACTIVE",
		2: "WORKSPACE_PHASE_TERMINATING",
	}
	WorkspacePhase_value = map[string]int32{
		"WORKSPACE_PHASE_UNSPECIFIED": 0,
		"WORKSPACE_PHASE_ACTIVE":      1,
		"WORKSPACE_PHASE_TERMINATING": 2,
	}
)

func (x WorkspacePhase) Enum() *WorkspacePhase {
	p := new(WorkspacePhase)
	*p = x
	return p
}

func (x WorkspacePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspacePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_datamodel_proto_enumTypes[0].Descriptor()
}

func (WorkspacePhase) Type() protoreflect.EnumType {
	return &file_datamodel_proto_enumTypes[0]
}

func (x WorkspacePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspacePhase.Descriptor instead.
func (WorkspacePhase) EnumDescriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{0}
}

// Selects the workspace scope for a public API request.
//
// Requests that operate on one workspace require a non-empty `workspace`.
// Cross-workspace list requests additionally accept `all_workspaces`. The
// containing request documents which selections it supports; an omitted
// selector is invalid for workspace-scoped operations.
type WorkspaceSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selection:
	//
	//	*WorkspaceSelector_Workspace
	//	*WorkspaceSelector_AllWorkspaces
	Selection     isWorkspaceSelector_Selection `protobuf_oneof:"selection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceSelector) Reset() {
	*x = WorkspaceSelector{}
	mi := &file_datamodel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSelector) ProtoMessage() {}

func (x *WorkspaceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSelector.ProtoReflect.Descriptor instead.
func (*WorkspaceSelector) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{0}
}

func (x *WorkspaceSelector) GetSelection() isWorkspaceSelector_Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *WorkspaceSelector) GetWorkspace() string {
	if x != nil {
		if x, ok := x.Selection.(*WorkspaceSelector_Workspace); ok {
			return x.Workspace
		}
	}
	return ""
}

func (x *WorkspaceSelector) GetAllWorkspaces() *AllWorkspaces {
	if x != nil {
		if x, ok := x.Selection.(*WorkspaceSelector_AllWorkspaces); ok {
			return x.AllWorkspaces
		}
	}
	return nil
}

type isWorkspaceSelector_Selection interface {
	isWorkspaceSelector_Selection()
}

type WorkspaceSelector_Workspace struct {
	// One explicitly named workspace. Use `default` to select the gateway's
	// default workspace; an empty name is invalid.
	Workspace string `protobuf:"bytes,1,opt,name=workspace,proto3,oneof"`
}

type WorkspaceSelector_AllWorkspaces struct {
	// All workspaces the caller is authorized to access. Only supported by
	// requests that explicitly document cross-workspace behavior.
	AllWorkspaces *AllWorkspaces `protobuf:"bytes,2,opt,name=all_workspaces,json=allWorkspaces,proto3,oneof"`
}

func (*WorkspaceSelector_Workspace) isWorkspaceSelector_Selection() {}

func (*WorkspaceSelector_AllWorkspaces) isWorkspaceSelector_Selection() {}

// Marker for the all-workspaces selector variant.
type AllWorkspaces struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllWorkspaces) Reset() {
	*x = AllWorkspaces{}
	mi := &file_datamodel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllWorkspaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllWorkspaces) ProtoMessage() {}

func (x *AllWorkspaces) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllWorkspaces.ProtoReflect.Descriptor instead.
func (*AllWorkspaces) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{1}
}

// Kubernetes-style metadata shared by all top-level OpenShell domain objects.
//
// This structure provides consistent metadata (identity, labels, annotations,
// timestamps, resource versioning) across Sandbox, Provider, SshSession, and
// other resources.
type ObjectMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable object ID generated by the gateway.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable object name (unique per object type).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Time when the object was created.
	CreatedTime *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// Key-value labels for filtering and organization.
	// Labels must follow Kubernetes conventions: alphanumeric + `-._/`, max 63 chars per segment.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optimistic concurrency control version.
	// Incremented by the gateway on each update. Clients can use this for compare-and-swap operations.
	ResourceVersion uint64 `protobuf:"varint,5,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// Opaque key-value metadata that is not used for selectors.
	// Annotation keys use the same qualified-key shape as labels, but values may be longer.
	Annotations map[string]string `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Workspace that owns this resource. Empty is normalized to "default" by the
	// gateway. Immutable after creation.
	Workspace string `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// Time when graceful deletion was initiated. Absence means the object is
	// not being deleted. Once set, this field is
	// immutable — the only path forward is completing deletion.
	DeletionTime  *timestamppb.Timestamp `protobuf:"bytes,108,opt,name=deletion_time,json=deletionTime,proto3" json:"deletion_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_datamodel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetCreatedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTime
	}
	return nil
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetResourceVersion() uint64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *ObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ObjectMeta) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ObjectMeta) GetDeletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTime
	}
	return nil
}

// Status of a workspace.
type WorkspaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         WorkspacePhase         `protobuf:"varint,1,opt,name=phase,proto3,enum=openshell.datamodel.v1.WorkspacePhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceStatus) Reset() {
	*x = WorkspaceStatus{}
	mi := &file_datamodel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStatus) ProtoMessage() {}

func (x *WorkspaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStatus.ProtoReflect.Descriptor instead.
func (*WorkspaceStatus) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceStatus) GetPhase() WorkspacePhase {
	if x != nil {
		return x.Phase
	}
	return WorkspacePhase_WORKSPACE_PHASE_UNSPECIFIED
}

// Workspace resource. A hard isolation boundary for sandboxes, providers, and
// other workspace-scoped resources.
type Workspace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes-style metadata (id, name, labels, timestamps, resource version).
	// The workspace field in this ObjectMeta is unused (a workspace does not
	// belong to another workspace).
	Metadata *ObjectMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Current lifecycle status.
	Status        *WorkspaceStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_datamodel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{4}
}

func (x *Workspace) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Workspace) GetStatus() *WorkspaceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Opaque handle for a provider credential stored by gateway credential storage.
// Handles are created by OpenShell and must not be authored by users.
type CredentialHandle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal storage owner or credential driver that owns this handle.
	Driver string `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	// Owner-owned opaque handle string.
	Handle string `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	// Owner-owned non-secret metadata.
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialHandle) Reset() {
	*x = CredentialHandle{}
	mi := &file_datamodel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialHandle) ProtoMessage() {}

func (x *CredentialHandle) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialHandle.ProtoReflect.Descriptor instead.
func (*CredentialHandle) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{5}
}

func (x *CredentialHandle) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CredentialHandle) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *CredentialHandle) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Provider model stored by OpenShell.
type Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes-style metadata (id, name, labels, timestamps, resource version).
	Metadata *ObjectMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// ID of the provider profile this provider was created from, matched
	// exactly (for example: "claude-code", "github").
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Secret values used for authentication.
	Credentials map[string]string `protobuf:"bytes,3,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Non-secret provider configuration.
	Config map[string]string `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Expiration times for credential values, keyed by credential/env var name.
	// A missing key means the credential does not expire.
	CredentialExpirationTimes map[string]*timestamppb.Timestamp `protobuf:"bytes,105,rep,name=credential_expiration_times,json=credentialExpirationTimes,proto3" json:"credential_expiration_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Workspace where this provider's type profile is stored.
	// Empty string = platform/global scope. Must be empty or match
	// metadata.workspace; cross-workspace references are rejected.
	ProfileWorkspace string `protobuf:"bytes,6,opt,name=profile_workspace,json=profileWorkspace,proto3" json:"profile_workspace,omitempty"`
	// Opaque handles for secret values stored through gateway credential storage.
	// This map is internal gateway state and is not accepted as user-authored input.
	CredentialHandles map[string]*CredentialHandle `protobuf:"bytes,7,rep,name=credential_handles,json=credentialHandles,proto3" json:"credential_handles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_datamodel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_datamodel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_datamodel_proto_rawDescGZIP(), []int{6}
}

func (x *Provider) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Provider) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Provider) GetCredentialExpirationTimes() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.CredentialExpirationTimes
	}
	return nil
}

func (x *Provider) GetProfileWorkspace() string {
	if x != nil {
		return x.ProfileWorkspace
	}
	return ""
}

func (x *Provider) GetCredentialHandles() map[string]*CredentialHandle {
	if x != nil {
		return x.CredentialHandles
	}
	return nil
}

var File_datamodel_proto protoreflect.FileDescriptor

const file_datamodel_proto_rawDesc = "" +
	"\n" +
	"\x0fdatamodel.proto\x12\x16openshell.datamodel.v1\x1a\roptions.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x11WorkspaceSelector\x12\x1e\n" +
	"\tworkspace\x18\x01 \x01(\tH\x00R\tworkspace\x12N\n" +
	"\x0eall_workspaces\x18\x02 \x01(\v2%.openshell.datamodel.v1.AllWorkspacesH\x00R\rallWorkspacesB\v\n" +
	"\tselection\"\x0f\n" +
	"\rAllWorkspaces\"\xc5\x04\n" +
	"\n" +
	"ObjectMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12=\n" +
	"\fcreated_time\x18g \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedTime\x12F\n" +
	"\x06labels\x18\x04 \x03(\v2..openshell.datamodel.v1.ObjectMeta.LabelsEntryR\x06labels\x12)\n" +
	"\x10resource_version\x18\x05 \x01(\x04R\x0fresourceVersion\x12U\n" +
	"\vannotations\x18\x06 \x03(\v23.openshell.datamodel.v1.ObjectMeta.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tworkspace\x18\a \x01(\tR\tworkspace\x12?\n" +
	"\rdeletion_time\x18l \x01(\v2\x1a.google.protobuf.TimestampR\fdeletionTime\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x03\x10\x04J\x04\b\b\x10\tR\rcreated_at_msR\x15deletion_timestamp_ms\"O\n" +
	"\x0fWorkspaceStatus\x12<\n" +
	"\x05phase\x18\x01 \x01(\x0e2&.openshell.datamodel.v1.WorkspacePhaseR\x05phase\"\x8c\x01\n" +
	"\tWorkspace\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".openshell.datamodel.v1.ObjectMetaR\bmetadata\x12?\n" +
	"\x06status\x18\x02 \x01(\v2'.openshell.datamodel.v1.WorkspaceStatusR\x06status\"\xd3\x01\n" +
	"\x10CredentialHandle\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12R\n" +
	"\bmetadata\x18\x03 \x03(\v26.openshell.datamodel.v1.CredentialHandle.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\a\n" +
	"\bProvider\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".openshell.datamodel.v1.ObjectMetaR\bmetadata\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12Y\n" +
	"\vcredentials\x18\x03 \x03(\v21.openshell.datamodel.v1.Provider.CredentialsEntryB\x04\x88\xb5\x18\x01R\vcredentials\x12D\n" +
	"\x06config\x18\x04 \x03(\v2,.openshell.datamodel.v1.Provider.ConfigEntryR\x06config\x12\x7f\n" +
	"\x1bcredential_expiration_times\x18i \x03(\v2?.openshell.datamodel.v1.Provider.CredentialExpirationTimesEntryR\x19credentialExpirationTimes\x12+\n" +
	"\x11profile_workspace\x18\x06 \x01(\tR\x10profileWorkspace\x12f\n" +
	"\x12credential_handles\x18\a \x03(\v27.openshell.datamodel.v1.Provider.CredentialHandlesEntryR\x11credentialHandles\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ah\n" +
	"\x1eCredentialExpirationTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1an\n" +
	"\x16CredentialHandlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.openshell.datamodel.v1.CredentialHandleR\x05value:\x028\x01J\x04\b\x05\x10\x06R\x18credential_expires_at_ms*n\n" +
	"\x0eWorkspacePhase\x12\x1f\n" +
	"\x1bWORKSPACE_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKSPACE_PHASE_ACTIVE\x10\x01\x12\x1f\n" +
	"\x1bWORKSPACE_PHASE_TERMINATING\x10\x02b\x06proto3"

var (
	file_datamodel_proto_rawDescOnce sync.Once
	file_datamodel_proto_rawDescData []byte
)

func file_datamodel_proto_rawDescGZIP() []byte {
	file_datamodel_proto_rawDescOnce.Do(func() {
		file_datamodel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datamodel_proto_rawDesc), len(file_datamodel_proto_rawDesc)))
	})
	return file_datamodel_proto_rawDescData
}

var file_datamodel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_datamodel_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_datamodel_proto_goTypes = []any{
	(WorkspacePhase)(0),           // 0: openshell.datamodel.v1.WorkspacePhase
	(*WorkspaceSelector)(nil),     // 1: openshell.datamodel.v1.WorkspaceSelector
	(*AllWorkspaces)(nil),         // 2: openshell.datamodel.v1.AllWorkspaces
	(*ObjectMeta)(nil),            // 3: openshell.datamodel.v1.ObjectMeta
	(*WorkspaceStatus)(nil),       // 4: openshell.datamodel.v1.WorkspaceStatus
	(*Workspace)(nil),             // 5: openshell.datamodel.v1.Workspace
	(*CredentialHandle)(nil),      // 6: openshell.datamodel.v1.CredentialHandle
	(*Provider)(nil),              // 7: openshell.datamodel.v1.Provider
	nil,                           // 8: openshell.datamodel.v1.ObjectMeta.LabelsEntry
	nil,                           // 9: openshell.datamodel.v1.ObjectMeta.AnnotationsEntry
	nil,                           // 10: openshell.datamodel.v1.CredentialHandle.MetadataEntry
	nil,                           // 11: openshell.datamodel.v1.Provider.CredentialsEntry
	nil,                           // 12: openshell.datamodel.v1.Provider.ConfigEntry
	nil,                           // 13: openshell.datamodel.v1.Provider.CredentialExpirationTimesEntry
	nil,                           // 14: openshell.datamodel.v1.Provider.CredentialHandlesEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_datamodel_proto_depIdxs = []int32{
	2,  // 0: openshell.datamodel.v1.WorkspaceSelector.all_workspaces:type_name -> openshell.datamodel.v1.AllWorkspaces
	15, // 1: openshell.datamodel.v1.ObjectMeta.created_time:type_name -> google.protobuf.Timestamp
	8,  // 2: openshell.datamodel.v1.ObjectMeta.labels:type_name -> openshell.datamodel.v1.ObjectMeta.LabelsEntry
	9,  // 3: openshell.datamodel.v1.ObjectMeta.annotations:type_name -> openshell.datamodel.v1.ObjectMeta.AnnotationsEntry
	15, // 4: openshell.datamodel.v1.ObjectMeta.deletion_time:type_name -> google.protobuf.Timestamp
	0,  // 5: openshell.datamodel.v1.WorkspaceStatus.phase:type_name -> openshell.datamodel.v1.WorkspacePhase
	3,  // 6: openshell.datamodel.v1.Workspace.metadata:type_name -> openshell.datamodel.v1.ObjectMeta
	4,  // 7: openshell.datamodel.v1.Workspace.status:type_name -> openshell.datamodel.v1.WorkspaceStatus
	10, // 8: openshell.datamodel.v1.CredentialHandle.metadata:type_name -> openshell.datamodel.v1.CredentialHandle.MetadataEntry
	3,  // 9: openshell.datamodel.v1.Provider.metadata:type_name -> openshell.datamodel.v1.ObjectMeta
	11, // 10: openshell.datamodel.v1.Provider.credentials:type_name -> openshell.datamodel.v1.Provider.CredentialsEntry
	12, // 11: openshell.datamodel.v1.Provider.config:type_name -> openshell.datamodel.v1.Provider.ConfigEntry
	13, // 12: openshell.datamodel.v1.Provider.credential_expiration_times:type_name -> openshell.datamodel.v1.Provider.CredentialExpirationTimesEntry
	14, // 13: openshell.datamodel.v1.Provider.credential_handles:type_name -> openshell.datamodel.v1.Provider.CredentialHandlesEntry
	15, // 14: openshell.datamodel.v1.Provider.CredentialExpirationTimesEntry.value:type_name -> google.protobuf.Timestamp
	6,  // 15: openshell.datamodel.v1.Provider.CredentialHandlesEntry.value:type_name -> openshell.datamodel.v1.CredentialHandle
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_datamodel_proto_init() }
func file_datamodel_proto_init() {
	if File_datamodel_proto != nil {
		return
	}
	file_datamodel_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkspaceSelector_Workspace)(nil),
		(*WorkspaceSelector_AllWorkspaces)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datamodel_proto_rawDesc), len(file_datamodel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datamodel_proto_goTypes,
		DependencyIndexes: file_datamodel_proto_depIdxs,
		EnumInfos:         file_datamodel_proto_enumTypes,
		MessageInfos:      file_datamodel_proto_msgTypes,
	}.Build()
	File_datamodel_proto = out.File
	file_datamodel_proto_goTypes = nil
	file_datamodel_proto_depIdxs = nil
}
