// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sandbox.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scope that currently controls a setting.
type SettingScope int32

const (
	SettingScope_SETTING_SCOPE_UNSPECIFIED SettingScope = 0
	SettingScope_SETTING_SCOPE_SANDBOX     SettingScope = 1
	SettingScope_SETTING_SCOPE_GLOBAL      SettingScope = 2
)

// Enum value maps for SettingScope.
var (
	SettingScope_name = map[int32]string{
		0: "SETTING_SCOPE_UNSPECIFIED",
		1: "SETTING_SCOPE_SANDBOX",
		2: "SETTING_SCOPE_GLOBAL",
	}
	SettingScope_value = map[string]int32{
		"SETTING_SCOPE_UNSPECIFIED": 0,
		"SETTING_SCOPE_SANDBOX":     1,
		"SETTING_SCOPE_GLOBAL":      2,
	}
)

func (x SettingScope) Enum() *SettingScope {
	p := new(SettingScope)
	*p = x
	return p
}

func (x SettingScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettingScope) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[0].Descriptor()
}

func (SettingScope) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[0]
}

func (x SettingScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettingScope.Descriptor instead.
func (SettingScope) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

// Source used for the policy payload in GetSandboxConfigResponse.
type PolicySource int32

const (
	PolicySource_POLICY_SOURCE_UNSPECIFIED PolicySource = 0
	PolicySource_POLICY_SOURCE_SANDBOX     PolicySource = 1
	PolicySource_POLICY_SOURCE_GLOBAL      PolicySource = 2
)

// Enum value maps for PolicySource.
var (
	PolicySource_name = map[int32]string{
		0: "POLICY_SOURCE_UNSPECIFIED",
		1: "POLICY_SOURCE_SANDBOX",
		2: "POLICY_SOURCE_GLOBAL",
	}
	PolicySource_value = map[string]int32{
		"POLICY_SOURCE_UNSPECIFIED": 0,
		"POLICY_SOURCE_SANDBOX":     1,
		"POLICY_SOURCE_GLOBAL":      2,
	}
)

func (x PolicySource) Enum() *PolicySource {
	p := new(PolicySource)
	*p = x
	return p
}

func (x PolicySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicySource) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_proto_enumTypes[1].Descriptor()
}

func (PolicySource) Type() protoreflect.EnumType {
	return &file_sandbox_proto_enumTypes[1]
}

func (x PolicySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicySource.Descriptor instead.
func (PolicySource) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

// Sandbox security policy configuration.
type SandboxPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy version.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Filesystem access policy.
	Filesystem *FilesystemPolicy `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	// Landlock configuration.
	Landlock *LandlockPolicy `protobuf:"bytes,3,opt,name=landlock,proto3" json:"landlock,omitempty"`
	// Process execution policy.
	Process *ProcessPolicy `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	// Network access policies keyed by name (e.g. "claude_code", "gitlab").
	NetworkPolicies map[string]*NetworkPolicyRule `protobuf:"bytes,5,rep,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Reusable supervisor middleware configs for network egress, keyed by their
	// policy-local names. At most 10 configs are accepted, and at most 10 stages
	// can be selected per request.
	NetworkMiddlewares map[string]*NetworkMiddlewareConfig `protobuf:"bytes,6,rep,name=network_middlewares,json=networkMiddlewares,proto3" json:"network_middlewares,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxPolicy) Reset() {
	*x = SandboxPolicy{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPolicy) ProtoMessage() {}

func (x *SandboxPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPolicy.ProtoReflect.Descriptor instead.
func (*SandboxPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxPolicy) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SandboxPolicy) GetFilesystem() *FilesystemPolicy {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *SandboxPolicy) GetLandlock() *LandlockPolicy {
	if x != nil {
		return x.Landlock
	}
	return nil
}

func (x *SandboxPolicy) GetProcess() *ProcessPolicy {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkPolicies() map[string]*NetworkPolicyRule {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkMiddlewares() map[string]*NetworkMiddlewareConfig {
	if x != nil {
		return x.NetworkMiddlewares
	}
	return nil
}

// Filesystem access policy.
type FilesystemPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Automatically include the workdir as read-write.
	IncludeWorkdir bool `protobuf:"varint,1,opt,name=include_workdir,json=includeWorkdir,proto3" json:"include_workdir,omitempty"`
	// Read-only directory allow list.
	ReadOnly []string `protobuf:"bytes,2,rep,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Read-write directory allow list.
	ReadWrite     []string `protobuf:"bytes,3,rep,name=read_write,json=readWrite,proto3" json:"read_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemPolicy) Reset() {
	*x = FilesystemPolicy{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPolicy) ProtoMessage() {}

func (x *FilesystemPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPolicy.ProtoReflect.Descriptor instead.
func (*FilesystemPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *FilesystemPolicy) GetIncludeWorkdir() bool {
	if x != nil {
		return x.IncludeWorkdir
	}
	return false
}

func (x *FilesystemPolicy) GetReadOnly() []string {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

func (x *FilesystemPolicy) GetReadWrite() []string {
	if x != nil {
		return x.ReadWrite
	}
	return nil
}

// Landlock policy configuration.
type LandlockPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Compatibility mode (e.g. "best_effort", "hard_requirement").
	Compatibility string `protobuf:"bytes,1,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandlockPolicy) Reset() {
	*x = LandlockPolicy{}
	mi := &file_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandlockPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlockPolicy) ProtoMessage() {}

func (x *LandlockPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlockPolicy.ProtoReflect.Descriptor instead.
func (*LandlockPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *LandlockPolicy) GetCompatibility() string {
	if x != nil {
		return x.Compatibility
	}
	return ""
}

// Process execution policy.
type ProcessPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User name to run the sandboxed process as.
	RunAsUser string `protobuf:"bytes,1,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	// Group name to run the sandboxed process as.
	RunAsGroup    string `protobuf:"bytes,2,opt,name=run_as_group,json=runAsGroup,proto3" json:"run_as_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPolicy) Reset() {
	*x = ProcessPolicy{}
	mi := &file_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPolicy) ProtoMessage() {}

func (x *ProcessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPolicy.ProtoReflect.Descriptor instead.
func (*ProcessPolicy) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPolicy) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *ProcessPolicy) GetRunAsGroup() string {
	if x != nil {
		return x.RunAsGroup
	}
	return ""
}

// A named network access policy rule.
type NetworkPolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for this policy rule.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Allowed endpoint (host:port) pairs.
	Endpoints []*NetworkEndpoint `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Allowed binary identities.
	Binaries      []*NetworkBinary `protobuf:"bytes,3,rep,name=binaries,proto3" json:"binaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRule) Reset() {
	*x = NetworkPolicyRule{}
	mi := &file_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRule) ProtoMessage() {}

func (x *NetworkPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRule) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkPolicyRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyRule) GetEndpoints() []*NetworkEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkPolicyRule) GetBinaries() []*NetworkBinary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

// A reusable middleware config selected for admitted egress by host.
type NetworkMiddlewareConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for this middleware config.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Built-in middleware name or operator-owned registration name.
	Middleware string `protobuf:"bytes,2,opt,name=middleware,proto3" json:"middleware,omitempty"`
	// Service-specific configuration.
	Config *structpb.Struct `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// Failure behavior: "fail_closed" (default) or "fail_open".
	OnError string `protobuf:"bytes,4,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`
	// Host selector controlling which admitted destinations use this config.
	Endpoints *MiddlewareEndpointSelector `protobuf:"bytes,5,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Execution order. Values must be unique within a policy; lower values run first.
	Order         int32 `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMiddlewareConfig) Reset() {
	*x = NetworkMiddlewareConfig{}
	mi := &file_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMiddlewareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMiddlewareConfig) ProtoMessage() {}

func (x *NetworkMiddlewareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMiddlewareConfig.ProtoReflect.Descriptor instead.
func (*NetworkMiddlewareConfig) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkMiddlewareConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetMiddleware() string {
	if x != nil {
		return x.Middleware
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NetworkMiddlewareConfig) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetEndpoints() *MiddlewareEndpointSelector {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkMiddlewareConfig) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// Host selector controlling which admitted destinations use a middleware config.
type MiddlewareEndpointSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact host or DNS glob patterns included in the selection. Include and
	// exclude accept at most 32 combined patterns.
	Include []string `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	// Exact host or DNS glob patterns removed from the selection.
	// Exclusions take precedence over inclusions.
	Exclude       []string `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareEndpointSelector) Reset() {
	*x = MiddlewareEndpointSelector{}
	mi := &file_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareEndpointSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareEndpointSelector) ProtoMessage() {}

func (x *MiddlewareEndpointSelector) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareEndpointSelector.ProtoReflect.Descriptor instead.
func (*MiddlewareEndpointSelector) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *MiddlewareEndpointSelector) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *MiddlewareEndpointSelector) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

// Binds a policy endpoint to static credentials from a sandbox provider.
type NetworkCredentialBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the provider attached to this sandbox whose static credentials
	// may be resolved for requests admitted by this endpoint.
	Provider      string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCredentialBinding) Reset() {
	*x = NetworkCredentialBinding{}
	mi := &file_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCredentialBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCredentialBinding) ProtoMessage() {}

func (x *NetworkCredentialBinding) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCredentialBinding.ProtoReflect.Descriptor instead.
func (*NetworkCredentialBinding) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkCredentialBinding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// A network endpoint (host + port) with optional L7 inspection config.
type NetworkEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname or host glob pattern. Exact match is case-insensitive.
	// Glob patterns use "." as delimiter: "*.example.com" matches a single
	// subdomain label, "**.example.com" matches across labels.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Single port (backwards compat). Use `ports` for multiple ports.
	// Mutually exclusive with `ports` — if both are set, `ports` takes precedence.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Endpoint protocol. "tcp" and "" select L4-only handling; "rest",
	// "websocket", "graphql", "sql", "json-rpc", and "mcp" select L7 inspection.
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// TLS handling: "terminate" or "passthrough" (default).
	Tls string `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	// Enforcement mode: "enforce" or "audit" (default).
	Enforcement string `protobuf:"bytes,5,opt,name=enforcement,proto3" json:"enforcement,omitempty"`
	// Access preset shorthand: "read-only", "read-write", "full".
	// Mutually exclusive with rules.
	Access string `protobuf:"bytes,6,opt,name=access,proto3" json:"access,omitempty"`
	// Explicit L7 rules (mutually exclusive with access).
	Rules []*L7Rule `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	// Allowed resolved IP addresses or CIDR ranges for this endpoint.
	// When non-empty, the SSRF internal-IP check is replaced by an allowlist check:
	//   - If host is also set: domain must resolve to an IP in this list.
	//   - If host is empty: any domain is allowed as long as it resolves to an IP in this list.
	//
	// Supports exact IPs ("10.0.5.20") and CIDR notation ("10.0.5.0/24").
	// Loopback (127.0.0.0/8) and link-local (169.254.0.0/16) are always blocked
	// regardless of this field.
	AllowedIps []string `protobuf:"bytes,8,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	// Multiple ports. When non-empty, this endpoint covers all listed ports.
	// If `port` is set and `ports` is empty, `port` is normalized to `ports: [port]`.
	// If both are set, `ports` takes precedence.
	Ports []uint32 `protobuf:"varint,9,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	// Explicit L7 deny rules. When present, requests matching any deny rule
	// are blocked even if they match an allow rule or access preset.
	// Deny rules take precedence over allow rules.
	DenyRules []*L7DenyRule `protobuf:"bytes,10,rep,name=deny_rules,json=denyRules,proto3" json:"deny_rules,omitempty"`
	// When true, percent-encoded '/' (%2F) is preserved in path segments
	// rather than rejected by the L7 path canonicalizer. Required for
	// upstreams like GitLab that embed %2F in namespaced resource paths.
	// Defaults to false (strict).
	AllowEncodedSlash bool `protobuf:"varint,11,opt,name=allow_encoded_slash,json=allowEncodedSlash,proto3" json:"allow_encoded_slash,omitempty"`
	// GraphQL persisted-query behavior for hash-only/saved-query requests:
	// "deny" (default) or "allow_registered".
	PersistedQueries string `protobuf:"bytes,12,opt,name=persisted_queries,json=persistedQueries,proto3" json:"persisted_queries,omitempty"`
	// Trusted GraphQL persisted-query registry keyed by hash or service-specific ID.
	// Only used when persisted_queries is "allow_registered".
	GraphqlPersistedQueries map[string]*GraphqlOperation `protobuf:"bytes,13,rep,name=graphql_persisted_queries,json=graphqlPersistedQueries,proto3" json:"graphql_persisted_queries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Maximum GraphQL request body bytes to buffer for inspection.
	// Defaults to 65536 when unset.
	GraphqlMaxBodyBytes uint32 `protobuf:"varint,14,opt,name=graphql_max_body_bytes,json=graphqlMaxBodyBytes,proto3" json:"graphql_max_body_bytes,omitempty"`
	// Optional HTTP path glob that scopes this L7 endpoint on shared host:port APIs.
	// Example: use path "/graphql" for protocol "graphql" and "/repos/**" for
	// protocol "rest" when both surfaces live under api.example.com:443.
	// Empty means all paths.
	Path string `protobuf:"bytes,15,opt,name=path,proto3" json:"path,omitempty"`
	// When true on a "rest" endpoint, OpenShell rewrites credential placeholders
	// inside client-to-server WebSocket text messages after an allowed HTTP 101
	// upgrade. Defaults to false.
	WebsocketCredentialRewrite bool `protobuf:"varint,16,opt,name=websocket_credential_rewrite,json=websocketCredentialRewrite,proto3" json:"websocket_credential_rewrite,omitempty"`
	// When true on a "rest" endpoint, OpenShell rewrites credential placeholders
	// inside supported textual HTTP request bodies before forwarding upstream.
	// Defaults to false.
	RequestBodyCredentialRewrite bool `protobuf:"varint,17,opt,name=request_body_credential_rewrite,json=requestBodyCredentialRewrite,proto3" json:"request_body_credential_rewrite,omitempty"`
	// Internal provenance marker for policy-advisor generated endpoints.
	// Advisor-proposed endpoints must not satisfy exact-host SSRF trust unless
	// they are converted through an explicit user-authored policy path.
	AdvisorProposed bool `protobuf:"varint,18,opt,name=advisor_proposed,json=advisorProposed,proto3" json:"advisor_proposed,omitempty"`
	// Proxy-side credential signing mode: "sigv4" for AWS SigV4 re-signing.
	// When set, the proxy strips the client's Authorization header and computes
	// a fresh SigV4 signature using real credentials from the provider.
	CredentialSigning string `protobuf:"bytes,19,opt,name=credential_signing,json=credentialSigning,proto3" json:"credential_signing,omitempty"`
	// AWS signing service name override. Required when credential_signing is
	// "sigv4" — e.g. "bedrock" for bedrock-runtime endpoints.
	SigningService string `protobuf:"bytes,20,opt,name=signing_service,json=signingService,proto3" json:"signing_service,omitempty"`
	// AWS region override for SigV4 signing. When set, takes precedence over
	// hostname-based region extraction. Required for non-standard endpoints.
	SigningRegion string `protobuf:"bytes,21,opt,name=signing_region,json=signingRegion,proto3" json:"signing_region,omitempty"`
	// Maximum JSON-RPC-over-HTTP request body bytes to buffer for inspection.
	// Defaults to 65536 when unset.
	JsonRpcMaxBodyBytes uint32 `protobuf:"varint,22,opt,name=json_rpc_max_body_bytes,json=jsonRpcMaxBodyBytes,proto3" json:"json_rpc_max_body_bytes,omitempty"`
	// MCP-only policy and inspection options. Only used when protocol is "mcp".
	Mcp *McpOptions `protobuf:"bytes,23,opt,name=mcp,proto3" json:"mcp,omitempty"`
	// Explicit binding authority for static credentials from an attached
	// endpointless provider profile. Profiles that already define endpoints
	// continue to use those profile endpoints as their credential boundary.
	CredentialBinding *NetworkCredentialBinding `protobuf:"bytes,24,opt,name=credential_binding,json=credentialBinding,proto3" json:"credential_binding,omitempty"`
	// Explicitly permits credential-bearing traffic to use paths that OpenShell
	// cannot inspect or rewrite. Defaults to false. This is a security-sensitive
	// escape hatch and must be explicitly approved.
	AllowUninspectedCredentials bool `protobuf:"varint,25,opt,name=allow_uninspected_credentials,json=allowUninspectedCredentials,proto3" json:"allow_uninspected_credentials,omitempty"`
	// Internal gateway-derived marker indicating that this endpoint belongs to
	// an attached credentialed provider. User-authored values are ignored.
	ProviderCredentialed bool `protobuf:"varint,26,opt,name=provider_credentialed,json=providerCredentialed,proto3" json:"provider_credentialed,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEndpoint) GetTls() string {
	if x != nil {
		return x.Tls
	}
	return ""
}

func (x *NetworkEndpoint) GetEnforcement() string {
	if x != nil {
		return x.Enforcement
	}
	return ""
}

func (x *NetworkEndpoint) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *NetworkEndpoint) GetRules() []*L7Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *NetworkEndpoint) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NetworkEndpoint) GetDenyRules() []*L7DenyRule {
	if x != nil {
		return x.DenyRules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowEncodedSlash() bool {
	if x != nil {
		return x.AllowEncodedSlash
	}
	return false
}

func (x *NetworkEndpoint) GetPersistedQueries() string {
	if x != nil {
		return x.PersistedQueries
	}
	return ""
}

func (x *NetworkEndpoint) GetGraphqlPersistedQueries() map[string]*GraphqlOperation {
	if x != nil {
		return x.GraphqlPersistedQueries
	}
	return nil
}

func (x *NetworkEndpoint) GetGraphqlMaxBodyBytes() uint32 {
	if x != nil {
		return x.GraphqlMaxBodyBytes
	}
	return 0
}

func (x *NetworkEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NetworkEndpoint) GetWebsocketCredentialRewrite() bool {
	if x != nil {
		return x.WebsocketCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetRequestBodyCredentialRewrite() bool {
	if x != nil {
		return x.RequestBodyCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetAdvisorProposed() bool {
	if x != nil {
		return x.AdvisorProposed
	}
	return false
}

func (x *NetworkEndpoint) GetCredentialSigning() string {
	if x != nil {
		return x.CredentialSigning
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningService() string {
	if x != nil {
		return x.SigningService
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningRegion() string {
	if x != nil {
		return x.SigningRegion
	}
	return ""
}

func (x *NetworkEndpoint) GetJsonRpcMaxBodyBytes() uint32 {
	if x != nil {
		return x.JsonRpcMaxBodyBytes
	}
	return 0
}

func (x *NetworkEndpoint) GetMcp() *McpOptions {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *NetworkEndpoint) GetCredentialBinding() *NetworkCredentialBinding {
	if x != nil {
		return x.CredentialBinding
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowUninspectedCredentials() bool {
	if x != nil {
		return x.AllowUninspectedCredentials
	}
	return false
}

func (x *NetworkEndpoint) GetProviderCredentialed() bool {
	if x != nil {
		return x.ProviderCredentialed
	}
	return false
}

// MCP options are grouped so MCP-specific policy can grow without adding more
// top-level NetworkEndpoint fields. OpenShell owns the supported revision
// profiles instead of treating dependency enums as the policy contract.
//
// Sources:
// - https://modelcontextprotocol.io/specification/2025-03-26/basic/transports
// - https://modelcontextprotocol.io/specification/2025-06-18/basic/transports
// - https://modelcontextprotocol.io/specification/2025-11-25/basic/transports
type McpOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hardening boundary for tools/call params.name. When unset or true, the
	// supervisor enforces the MCP recommended tool-name syntax
	// ^[A-Za-z0-9_.-]{1,128}$ before policy evaluation. Set false only for
	// compatibility with servers that intentionally use non-recommended names.
	//
	// Source:
	// - https://modelcontextprotocol.io/specification/2025-11-25/server/tools#tool-names
	StrictToolNames *bool `protobuf:"varint,1,opt,name=strict_tool_names,json=strictToolNames,proto3,oneof" json:"strict_tool_names,omitempty"`
	// Method-layer default for MCP endpoints. When true, OpenShell allows parsed
	// MCP-family methods at the method layer unless a tool-name policy narrows
	// tools/call. When unset or false, explicit method rules are required.
	AllowAllKnownMcpMethods *bool `protobuf:"varint,2,opt,name=allow_all_known_mcp_methods,json=allowAllKnownMcpMethods,proto3,oneof" json:"allow_all_known_mcp_methods,omitempty"`
	// Exact MCP protocol revisions accepted by the endpoint's policy schema.
	// Authors may omit this field. Because proto3 repeated fields do not retain
	// presence, omission reaches protobuf ingress as an empty list. Checked
	// normalization materializes OpenShell's pinned default revision
	// "2025-11-25" before producing canonical downstream state, which is always
	// nonempty.
	//
	// An explicit nonempty list remains an exact allowlist. Duplicates, moving
	// aliases such as "draft" and "latest", and unknown dates are invalid.
	// Normalization stores valid values in canonical semantic order. These
	// values identify core revisions; they do not enable separate SEP overlays
	// or select runtime parsing and forwarding behavior.
	Versions      []string `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpOptions) Reset() {
	*x = McpOptions{}
	mi := &file_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpOptions) ProtoMessage() {}

func (x *McpOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpOptions.ProtoReflect.Descriptor instead.
func (*McpOptions) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *McpOptions) GetStrictToolNames() bool {
	if x != nil && x.StrictToolNames != nil {
		return *x.StrictToolNames
	}
	return false
}

func (x *McpOptions) GetAllowAllKnownMcpMethods() bool {
	if x != nil && x.AllowAllKnownMcpMethods != nil {
		return *x.AllowAllKnownMcpMethods
	}
	return false
}

func (x *McpOptions) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

// Trusted GraphQL operation classification.
type GraphqlOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation type: "query", "mutation", or "subscription".
	OperationType string `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	// Operation name, if known.
	OperationName string `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	// Root field names selected by the operation.
	Fields        []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphqlOperation) Reset() {
	*x = GraphqlOperation{}
	mi := &file_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphqlOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlOperation) ProtoMessage() {}

func (x *GraphqlOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlOperation.ProtoReflect.Descriptor instead.
func (*GraphqlOperation) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *GraphqlOperation) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *GraphqlOperation) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *GraphqlOperation) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// An L7 deny rule that blocks specific requests.
// Mirrors L7Allow — same fields, same matching semantics, inverted effect.
// Deny rules are evaluated after allow rules and take precedence.
type L7DenyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol method: HTTP method (REST/WebSocket), JSON-RPC method name, or
	// "*" for any when supported by the protocol.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// URL path glob pattern (REST): "/repos/*/pulls/*/reviews", "**" for any.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// SQL command (SQL): SELECT, INSERT, etc. or "*" for any.
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// Query parameter matcher map (REST).
	// Same semantics as L7Allow.query.
	Query map[string]*L7QueryMatcher `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// GraphQL operation type: "query", "mutation", "subscription", or "*" for any.
	OperationType string `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	// GraphQL operation name glob. "*" matches any operation name.
	OperationName string `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	// GraphQL root field globs. Deny rules match when any selected root field
	// matches any configured glob.
	Fields []string `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	// MCP params matcher map. Currently only params.name is supported for
	// tools/call filtering. Generic protocol "json-rpc" rejects params matchers.
	Params        map[string]*L7QueryMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7DenyRule) Reset() {
	*x = L7DenyRule{}
	mi := &file_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7DenyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7DenyRule) ProtoMessage() {}

func (x *L7DenyRule) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7DenyRule.ProtoReflect.Descriptor instead.
func (*L7DenyRule) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *L7DenyRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7DenyRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7DenyRule) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7DenyRule) GetQuery() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7DenyRule) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7DenyRule) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7DenyRule) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7DenyRule) GetParams() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

// An L7 policy rule (allow-only).
type L7Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         *L7Allow               `protobuf:"bytes,1,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Rule) Reset() {
	*x = L7Rule{}
	mi := &file_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Rule) ProtoMessage() {}

func (x *L7Rule) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Rule.ProtoReflect.Descriptor instead.
func (*L7Rule) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *L7Rule) GetAllow() *L7Allow {
	if x != nil {
		return x.Allow
	}
	return nil
}

// Allowed action definition for L7 rules.
type L7Allow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol method: HTTP method (REST/WebSocket), JSON-RPC method name, or
	// "*" for any when supported by the protocol.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// URL path glob pattern (REST): "/repos/**", "**" for any.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// SQL command (SQL): SELECT, INSERT, etc. or "*" for any.
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// Query parameter matcher map (REST).
	// Key is the decoded query parameter name (case-sensitive).
	// Value supports either a single glob (`glob`) or a list (`any`).
	Query map[string]*L7QueryMatcher `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// GraphQL operation type: "query", "mutation", "subscription", or "*" for any.
	OperationType string `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	// GraphQL operation name glob. "*" matches any operation name.
	OperationName string `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	// GraphQL root field globs. Allow rules match only when every selected root
	// field matches one of the configured globs. Omit to match all fields.
	Fields []string `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	// MCP params matcher map. Currently only params.name is supported for
	// tools/call filtering. Generic protocol "json-rpc" rejects params matchers.
	Params        map[string]*L7QueryMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Allow) Reset() {
	*x = L7Allow{}
	mi := &file_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Allow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Allow) ProtoMessage() {}

func (x *L7Allow) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Allow.ProtoReflect.Descriptor instead.
func (*L7Allow) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *L7Allow) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7Allow) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7Allow) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7Allow) GetQuery() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7Allow) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7Allow) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7Allow) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7Allow) GetParams() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

// Query value matcher for one query parameter key.
type L7QueryMatcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single glob pattern.
	Glob string `protobuf:"bytes,1,opt,name=glob,proto3" json:"glob,omitempty"`
	// Any-of glob patterns.
	Any           []string `protobuf:"bytes,2,rep,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7QueryMatcher) Reset() {
	*x = L7QueryMatcher{}
	mi := &file_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7QueryMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7QueryMatcher) ProtoMessage() {}

func (x *L7QueryMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7QueryMatcher.ProtoReflect.Descriptor instead.
func (*L7QueryMatcher) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *L7QueryMatcher) GetGlob() string {
	if x != nil {
		return x.Glob
	}
	return ""
}

func (x *L7QueryMatcher) GetAny() []string {
	if x != nil {
		return x.Any
	}
	return nil
}

// A binary identity for network policy matching.
type NetworkBinary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Deprecated: the harness concept has been removed. This field is ignored.
	//
	// Deprecated: Marked as deprecated in sandbox.proto.
	Harness       bool `protobuf:"varint,2,opt,name=harness,proto3" json:"harness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBinary) Reset() {
	*x = NetworkBinary{}
	mi := &file_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBinary) ProtoMessage() {}

func (x *NetworkBinary) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBinary.ProtoReflect.Descriptor instead.
func (*NetworkBinary) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkBinary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Deprecated: Marked as deprecated in sandbox.proto.
func (x *NetworkBinary) GetHarness() bool {
	if x != nil {
		return x.Harness
	}
	return false
}

// Request to get sandbox settings by sandbox ID.
type GetSandboxConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sandbox ID.
	SandboxId     string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxConfigRequest) Reset() {
	*x = GetSandboxConfigRequest{}
	mi := &file_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxConfigRequest) ProtoMessage() {}

func (x *GetSandboxConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxConfigRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *GetSandboxConfigRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

// Request to get gateway-global settings.
type GetGatewayConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayConfigRequest) Reset() {
	*x = GetGatewayConfigRequest{}
	mi := &file_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigRequest) ProtoMessage() {}

func (x *GetGatewayConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{17}
}

// Response containing gateway-global settings.
type GetGatewayConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway-global settings map excluding the reserved policy key.
	// Registered keys without a configured value are returned with an empty SettingValue.
	Settings map[string]*SettingValue `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Monotonically increasing revision for gateway-global settings.
	SettingsRevision uint64 `protobuf:"varint,2,opt,name=settings_revision,json=settingsRevision,proto3" json:"settings_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGatewayConfigResponse) Reset() {
	*x = GetGatewayConfigResponse{}
	mi := &file_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigResponse) ProtoMessage() {}

func (x *GetGatewayConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *GetGatewayConfigResponse) GetSettings() map[string]*SettingValue {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetGatewayConfigResponse) GetSettingsRevision() uint64 {
	if x != nil {
		return x.SettingsRevision
	}
	return 0
}

// Type-aware setting value for sandbox/gateway settings.
type SettingValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SettingValue_StringValue
	//	*SettingValue_BoolValue
	//	*SettingValue_IntValue
	//	*SettingValue_BytesValue
	Value         isSettingValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingValue) Reset() {
	*x = SettingValue{}
	mi := &file_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingValue) ProtoMessage() {}

func (x *SettingValue) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingValue.ProtoReflect.Descriptor instead.
func (*SettingValue) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *SettingValue) GetValue() isSettingValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SettingValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *SettingValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *SettingValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *SettingValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*SettingValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isSettingValue_Value interface {
	isSettingValue_Value()
}

type SettingValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type SettingValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type SettingValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type SettingValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*SettingValue_StringValue) isSettingValue_Value() {}

func (*SettingValue_BoolValue) isSettingValue_Value() {}

func (*SettingValue_IntValue) isSettingValue_Value() {}

func (*SettingValue_BytesValue) isSettingValue_Value() {}

// Effective setting value and the scope it was resolved from.
type EffectiveSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *SettingValue          `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Scope         SettingScope           `protobuf:"varint,2,opt,name=scope,proto3,enum=openshell.sandbox.v1.SettingScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectiveSetting) Reset() {
	*x = EffectiveSetting{}
	mi := &file_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectiveSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectiveSetting) ProtoMessage() {}

func (x *EffectiveSetting) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectiveSetting.ProtoReflect.Descriptor instead.
func (*EffectiveSetting) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *EffectiveSetting) GetValue() *SettingValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EffectiveSetting) GetScope() SettingScope {
	if x != nil {
		return x.Scope
	}
	return SettingScope_SETTING_SCOPE_UNSPECIFIED
}

// Response containing effective sandbox settings and policy.
type GetSandboxConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sandbox policy configuration.
	Policy *SandboxPolicy `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	// Current policy version (monotonically increasing per sandbox).
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// SHA-256 hash of the serialized policy payload.
	PolicyHash string `protobuf:"bytes,3,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	// Effective settings resolved for this sandbox, excluding the reserved policy key.
	// Registered keys without a configured value are returned with an empty EffectiveSetting.value.
	Settings map[string]*EffectiveSetting `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Fingerprint for effective config (policy + settings). Changes when any effective input changes.
	ConfigRevision uint64 `protobuf:"varint,5,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	// Source of the policy payload for this response.
	PolicySource PolicySource `protobuf:"varint,6,opt,name=policy_source,json=policySource,proto3,enum=openshell.sandbox.v1.PolicySource" json:"policy_source,omitempty"`
	// When policy_source is GLOBAL, the version of the global policy revision.
	// Zero when no global policy is active or when policy_source is SANDBOX.
	GlobalPolicyVersion uint32 `protobuf:"varint,7,opt,name=global_policy_version,json=globalPolicyVersion,proto3" json:"global_policy_version,omitempty"`
	// Fingerprint for provider credential inputs attached to this sandbox.
	// Changes when attached provider names or attached provider records change.
	ProviderEnvRevision uint64 `protobuf:"varint,8,opt,name=provider_env_revision,json=providerEnvRevision,proto3" json:"provider_env_revision,omitempty"`
	// Operator-registered supervisor middleware services required by the
	// effective policy. Built-in middleware is not included.
	SupervisorMiddlewareServices []*SupervisorMiddlewareService `protobuf:"bytes,9,rep,name=supervisor_middleware_services,json=supervisorMiddlewareServices,proto3" json:"supervisor_middleware_services,omitempty"`
	// Workspace the sandbox belongs to. Allows the supervisor to learn its
	// workspace context for subsequent workspace-scoped RPCs.
	Workspace string `protobuf:"bytes,10,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// Gateway-configured posture for rejected policy generations. Valid values
	// are "fail_closed" and "retain_last_valid". Unknown or empty values must
	// be treated as fail_closed by the supervisor.
	PolicyValidationFailureMode string `protobuf:"bytes,11,opt,name=policy_validation_failure_mode,json=policyValidationFailureMode,proto3" json:"policy_validation_failure_mode,omitempty"`
	// Whether this gateway can mint authenticated extension credentials.
	// False also covers older gateways that do not advertise this capability;
	// supervisors preserve their legacy unauthenticated connection behavior.
	ExtensionAuthenticationEnabled bool `protobuf:"varint,12,opt,name=extension_authentication_enabled,json=extensionAuthenticationEnabled,proto3" json:"extension_authentication_enabled,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetSandboxConfigResponse) Reset() {
	*x = GetSandboxConfigResponse{}
	mi := &file_sandbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxConfigResponse) ProtoMessage() {}

func (x *GetSandboxConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxConfigResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxConfigResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{21}
}

func (x *GetSandboxConfigResponse) GetPolicy() *SandboxPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *GetSandboxConfigResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetSettings() map[string]*EffectiveSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetSandboxConfigResponse) GetConfigRevision() uint64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetPolicySource() PolicySource {
	if x != nil {
		return x.PolicySource
	}
	return PolicySource_POLICY_SOURCE_UNSPECIFIED
}

func (x *GetSandboxConfigResponse) GetGlobalPolicyVersion() uint32 {
	if x != nil {
		return x.GlobalPolicyVersion
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetProviderEnvRevision() uint64 {
	if x != nil {
		return x.ProviderEnvRevision
	}
	return 0
}

func (x *GetSandboxConfigResponse) GetSupervisorMiddlewareServices() []*SupervisorMiddlewareService {
	if x != nil {
		return x.SupervisorMiddlewareServices
	}
	return nil
}

func (x *GetSandboxConfigResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetPolicyValidationFailureMode() string {
	if x != nil {
		return x.PolicyValidationFailureMode
	}
	return ""
}

func (x *GetSandboxConfigResponse) GetExtensionAuthenticationEnabled() bool {
	if x != nil {
		return x.ExtensionAuthenticationEnabled
	}
	return false
}

// Connection details for one operator-registered supervisor middleware service.
// V1 supports plaintext and server-authenticated TLS gRPC.
type SupervisorMiddlewareService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-owned registration name used by policy attachments and diagnostics.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// gRPC endpoint reachable from the sandbox supervisor.
	GrpcEndpoint string `protobuf:"bytes,2,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	// Operator-owned logical payload limit applied to every binding exposed by
	// the service. This caps HTTP bodies and complete WebSocket messages.
	MaxPayloadBytes uint64 `protobuf:"varint,3,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	// Default RPC timeout for this service. Empty uses the platform default of
	// 500ms. Values use an integer with an `ms` or `s` suffix and must be
	// between 10ms and 30s.
	Timeout string `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// PEM-encoded trust roots loaded by the gateway from the operator-configured
	// tls_ca_cert_path. Empty uses the platform trust store.
	TlsCaCertPem []byte `protobuf:"bytes,5,opt,name=tls_ca_cert_pem,json=tlsCaCertPem,proto3" json:"tls_ca_cert_pem,omitempty"`
	// Exact JWT audience for this service. The gateway resolves an omitted
	// operator value to a kind-scoped audience derived from the registration
	// name before sending sandbox config.
	Audience string `protobuf:"bytes,6,opt,name=audience,proto3" json:"audience,omitempty"`
	// Operator opt-out from extension authentication for this registration.
	// When true the service may use a plaintext endpoint and OpenShell attaches
	// no bearer credential; supervisors must not request one. Intended only for
	// trusted-network development deployments.
	AllowInsecureTransport bool `protobuf:"varint,7,opt,name=allow_insecure_transport,json=allowInsecureTransport,proto3" json:"allow_insecure_transport,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SupervisorMiddlewareService) Reset() {
	*x = SupervisorMiddlewareService{}
	mi := &file_sandbox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorMiddlewareService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorMiddlewareService) ProtoMessage() {}

func (x *SupervisorMiddlewareService) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorMiddlewareService.ProtoReflect.Descriptor instead.
func (*SupervisorMiddlewareService) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{22}
}

func (x *SupervisorMiddlewareService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SupervisorMiddlewareService) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *SupervisorMiddlewareService) GetMaxPayloadBytes() uint64 {
	if x != nil {
		return x.MaxPayloadBytes
	}
	return 0
}

func (x *SupervisorMiddlewareService) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *SupervisorMiddlewareService) GetTlsCaCertPem() []byte {
	if x != nil {
		return x.TlsCaCertPem
	}
	return nil
}

func (x *SupervisorMiddlewareService) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *SupervisorMiddlewareService) GetAllowInsecureTransport() bool {
	if x != nil {
		return x.AllowInsecureTransport
	}
	return false
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\x14openshell.sandbox.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa8\x05\n" +
	"\rSandboxPolicy\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12F\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\v2&.openshell.sandbox.v1.FilesystemPolicyR\n" +
	"filesystem\x12@\n" +
	"\blandlock\x18\x03 \x01(\v2$.openshell.sandbox.v1.LandlockPolicyR\blandlock\x12=\n" +
	"\aprocess\x18\x04 \x01(\v2#.openshell.sandbox.v1.ProcessPolicyR\aprocess\x12c\n" +
	"\x10network_policies\x18\x05 \x03(\v28.openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntryR\x0fnetworkPolicies\x12l\n" +
	"\x13network_middlewares\x18\x06 \x03(\v2;.openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntryR\x12networkMiddlewares\x1ak\n" +
	"\x14NetworkPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.openshell.sandbox.v1.NetworkPolicyRuleR\x05value:\x028\x01\x1at\n" +
	"\x17NetworkMiddlewaresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.openshell.sandbox.v1.NetworkMiddlewareConfigR\x05value:\x028\x01\"w\n" +
	"\x10FilesystemPolicy\x12'\n" +
	"\x0finclude_workdir\x18\x01 \x01(\bR\x0eincludeWorkdir\x12\x1b\n" +
	"\tread_only\x18\x02 \x03(\tR\breadOnly\x12\x1d\n" +
	"\n" +
	"read_write\x18\x03 \x03(\tR\treadWrite\"6\n" +
	"\x0eLandlockPolicy\x12$\n" +
	"\rcompatibility\x18\x01 \x01(\tR\rcompatibility\"Q\n" +
	"\rProcessPolicy\x12\x1e\n" +
	"\vrun_as_user\x18\x01 \x01(\tR\trunAsUser\x12 \n" +
	"\frun_as_group\x18\x02 \x01(\tR\n" +
	"runAsGroup\"\xad\x01\n" +
	"\x11NetworkPolicyRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\tendpoints\x18\x02 \x03(\v2%.openshell.sandbox.v1.NetworkEndpointR\tendpoints\x12?\n" +
	"\bbinaries\x18\x03 \x03(\v2#.openshell.sandbox.v1.NetworkBinaryR\bbinaries\"\xff\x01\n" +
	"\x17NetworkMiddlewareConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"middleware\x18\x02 \x01(\tR\n" +
	"middleware\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x19\n" +
	"\bon_error\x18\x04 \x01(\tR\aonError\x12N\n" +
	"\tendpoints\x18\x05 \x01(\v20.openshell.sandbox.v1.MiddlewareEndpointSelectorR\tendpoints\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\"P\n" +
	"\x1aMiddlewareEndpointSelector\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\"6\n" +
	"\x18NetworkCredentialBinding\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\xdc\n" +
	"\n" +
	"\x0fNetworkEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03tls\x18\x04 \x01(\tR\x03tls\x12 \n" +
	"\venforcement\x18\x05 \x01(\tR\venforcement\x12\x16\n" +
	"\x06access\x18\x06 \x01(\tR\x06access\x122\n" +
	"\x05rules\x18\a \x03(\v2\x1c.openshell.sandbox.v1.L7RuleR\x05rules\x12\x1f\n" +
	"\vallowed_ips\x18\b \x03(\tR\n" +
	"allowedIps\x12\x14\n" +
	"\x05ports\x18\t \x03(\rR\x05ports\x12?\n" +
	"\n" +
	"deny_rules\x18\n" +
	" \x03(\v2 .openshell.sandbox.v1.L7DenyRuleR\tdenyRules\x12.\n" +
	"\x13allow_encoded_slash\x18\v \x01(\bR\x11allowEncodedSlash\x12+\n" +
	"\x11persisted_queries\x18\f \x01(\tR\x10persistedQueries\x12~\n" +
	"\x19graphql_persisted_queries\x18\r \x03(\v2B.openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntryR\x17graphqlPersistedQueries\x123\n" +
	"\x16graphql_max_body_bytes\x18\x0e \x01(\rR\x13graphqlMaxBodyBytes\x12\x12\n" +
	"\x04path\x18\x0f \x01(\tR\x04path\x12@\n" +
	"\x1cwebsocket_credential_rewrite\x18\x10 \x01(\bR\x1awebsocketCredentialRewrite\x12E\n" +
	"\x1frequest_body_credential_rewrite\x18\x11 \x01(\bR\x1crequestBodyCredentialRewrite\x12)\n" +
	"\x10advisor_proposed\x18\x12 \x01(\bR\x0fadvisorProposed\x12-\n" +
	"\x12credential_signing\x18\x13 \x01(\tR\x11credentialSigning\x12'\n" +
	"\x0fsigning_service\x18\x14 \x01(\tR\x0esigningService\x12%\n" +
	"\x0esigning_region\x18\x15 \x01(\tR\rsigningRegion\x124\n" +
	"\x17json_rpc_max_body_bytes\x18\x16 \x01(\rR\x13jsonRpcMaxBodyBytes\x122\n" +
	"\x03mcp\x18\x17 \x01(\v2 .openshell.sandbox.v1.McpOptionsR\x03mcp\x12]\n" +
	"\x12credential_binding\x18\x18 \x01(\v2..openshell.sandbox.v1.NetworkCredentialBindingR\x11credentialBinding\x12B\n" +
	"\x1dallow_uninspected_credentials\x18\x19 \x01(\bR\x1ballowUninspectedCredentials\x123\n" +
	"\x15provider_credentialed\x18\x1a \x01(\bR\x14providerCredentialed\x1ar\n" +
	"\x1cGraphqlPersistedQueriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.openshell.sandbox.v1.GraphqlOperationR\x05value:\x028\x01\"\xd2\x01\n" +
	"\n" +
	"McpOptions\x12/\n" +
	"\x11strict_tool_names\x18\x01 \x01(\bH\x00R\x0fstrictToolNames\x88\x01\x01\x12A\n" +
	"\x1ballow_all_known_mcp_methods\x18\x02 \x01(\bH\x01R\x17allowAllKnownMcpMethods\x88\x01\x01\x12\x1a\n" +
	"\bversions\x18\x03 \x03(\tR\bversionsB\x14\n" +
	"\x12_strict_tool_namesB\x1e\n" +
	"\x1c_allow_all_known_mcp_methods\"x\n" +
	"\x10GraphqlOperation\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"\x88\x04\n" +
	"\n" +
	"L7DenyRule\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12A\n" +
	"\x05query\x18\x04 \x03(\v2+.openshell.sandbox.v1.L7DenyRule.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x12D\n" +
	"\x06params\x18\t \x03(\v2,.openshell.sandbox.v1.L7DenyRule.ParamsEntryR\x06params\x1a^\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01\x1a_\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01J\x04\b\b\x10\t\"=\n" +
	"\x06L7Rule\x123\n" +
	"\x05allow\x18\x01 \x01(\v2\x1d.openshell.sandbox.v1.L7AllowR\x05allow\"\xff\x03\n" +
	"\aL7Allow\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12>\n" +
	"\x05query\x18\x04 \x03(\v2(.openshell.sandbox.v1.L7Allow.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x12A\n" +
	"\x06params\x18\t \x03(\v2).openshell.sandbox.v1.L7Allow.ParamsEntryR\x06params\x1a^\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01\x1a_\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.openshell.sandbox.v1.L7QueryMatcherR\x05value:\x028\x01J\x04\b\b\x10\t\"6\n" +
	"\x0eL7QueryMatcher\x12\x12\n" +
	"\x04glob\x18\x01 \x01(\tR\x04glob\x12\x10\n" +
	"\x03any\x18\x02 \x03(\tR\x03any\"A\n" +
	"\rNetworkBinary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\aharness\x18\x02 \x01(\bB\x02\x18\x01R\aharness\"8\n" +
	"\x17GetSandboxConfigRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x19\n" +
	"\x17GetGatewayConfigRequest\"\x82\x02\n" +
	"\x18GetGatewayConfigResponse\x12X\n" +
	"\bsettings\x18\x01 \x03(\v2<.openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntryR\bsettings\x12+\n" +
	"\x11settings_revision\x18\x02 \x01(\x04R\x10settingsRevision\x1a_\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".openshell.sandbox.v1.SettingValueR\x05value:\x028\x01\"\x9f\x01\n" +
	"\fSettingValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\x86\x01\n" +
	"\x10EffectiveSetting\x128\n" +
	"\x05value\x18\x01 \x01(\v2\".openshell.sandbox.v1.SettingValueR\x05value\x128\n" +
	"\x05scope\x18\x02 \x01(\x0e2\".openshell.sandbox.v1.SettingScopeR\x05scope\"\xd1\x06\n" +
	"\x18GetSandboxConfigResponse\x12;\n" +
	"\x06policy\x18\x01 \x01(\v2#.openshell.sandbox.v1.SandboxPolicyR\x06policy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1f\n" +
	"\vpolicy_hash\x18\x03 \x01(\tR\n" +
	"policyHash\x12X\n" +
	"\bsettings\x18\x04 \x03(\v2<.openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntryR\bsettings\x12'\n" +
	"\x0fconfig_revision\x18\x05 \x01(\x04R\x0econfigRevision\x12G\n" +
	"\rpolicy_source\x18\x06 \x01(\x0e2\".openshell.sandbox.v1.PolicySourceR\fpolicySource\x122\n" +
	"\x15global_policy_version\x18\a \x01(\rR\x13globalPolicyVersion\x122\n" +
	"\x15provider_env_revision\x18\b \x01(\x04R\x13providerEnvRevision\x12w\n" +
	"\x1esupervisor_middleware_services\x18\t \x03(\v21.openshell.sandbox.v1.SupervisorMiddlewareServiceR\x1csupervisorMiddlewareServices\x12\x1c\n" +
	"\tworkspace\x18\n" +
	" \x01(\tR\tworkspace\x12C\n" +
	"\x1epolicy_validation_failure_mode\x18\v \x01(\tR\x1bpolicyValidationFailureMode\x12H\n" +
	" extension_authentication_enabled\x18\f \x01(\bR\x1eextensionAuthenticationEnabled\x1ac\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.openshell.sandbox.v1.EffectiveSettingR\x05value:\x028\x01\"\x99\x02\n" +
	"\x1bSupervisorMiddlewareService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rgrpc_endpoint\x18\x02 \x01(\tR\fgrpcEndpoint\x12*\n" +
	"\x11max_payload_bytes\x18\x03 \x01(\x04R\x0fmaxPayloadBytes\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\tR\atimeout\x12%\n" +
	"\x0ftls_ca_cert_pem\x18\x05 \x01(\fR\ftlsCaCertPem\x12\x1a\n" +
	"\baudience\x18\x06 \x01(\tR\baudience\x128\n" +
	"\x18allow_insecure_transport\x18\a \x01(\bR\x16allowInsecureTransport*b\n" +
	"\fSettingScope\x12\x1d\n" +
	"\x19SETTING_SCOPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SETTING_SCOPE_SANDBOX\x10\x01\x12\x18\n" +
	"\x14SETTING_SCOPE_GLOBAL\x10\x02*b\n" +
	"\fPolicySource\x12\x1d\n" +
	"\x19POLICY_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15POLICY_SOURCE_SANDBOX\x10\x01\x12\x18\n" +
	"\x14POLICY_SOURCE_GLOBAL\x10\x02b\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_sandbox_proto_goTypes = []any{
	(SettingScope)(0),                   // 0: openshell.sandbox.v1.SettingScope
	(PolicySource)(0),                   // 1: openshell.sandbox.v1.PolicySource
	(*SandboxPolicy)(nil),               // 2: openshell.sandbox.v1.SandboxPolicy
	(*FilesystemPolicy)(nil),            // 3: openshell.sandbox.v1.FilesystemPolicy
	(*LandlockPolicy)(nil),              // 4: openshell.sandbox.v1.LandlockPolicy
	(*ProcessPolicy)(nil),               // 5: openshell.sandbox.v1.ProcessPolicy
	(*NetworkPolicyRule)(nil),           // 6: openshell.sandbox.v1.NetworkPolicyRule
	(*NetworkMiddlewareConfig)(nil),     // 7: openshell.sandbox.v1.NetworkMiddlewareConfig
	(*MiddlewareEndpointSelector)(nil),  // 8: openshell.sandbox.v1.MiddlewareEndpointSelector
	(*NetworkCredentialBinding)(nil),    // 9: openshell.sandbox.v1.NetworkCredentialBinding
	(*NetworkEndpoint)(nil),             // 10: openshell.sandbox.v1.NetworkEndpoint
	(*McpOptions)(nil),                  // 11: openshell.sandbox.v1.McpOptions
	(*GraphqlOperation)(nil),            // 12: openshell.sandbox.v1.GraphqlOperation
	(*L7DenyRule)(nil),                  // 13: openshell.sandbox.v1.L7DenyRule
	(*L7Rule)(nil),                      // 14: openshell.sandbox.v1.L7Rule
	(*L7Allow)(nil),                     // 15: openshell.sandbox.v1.L7Allow
	(*L7QueryMatcher)(nil),              // 16: openshell.sandbox.v1.L7QueryMatcher
	(*NetworkBinary)(nil),               // 17: openshell.sandbox.v1.NetworkBinary
	(*GetSandboxConfigRequest)(nil),     // 18: openshell.sandbox.v1.GetSandboxConfigRequest
	(*GetGatewayConfigRequest)(nil),     // 19: openshell.sandbox.v1.GetGatewayConfigRequest
	(*GetGatewayConfigResponse)(nil),    // 20: openshell.sandbox.v1.GetGatewayConfigResponse
	(*SettingValue)(nil),                // 21: openshell.sandbox.v1.SettingValue
	(*EffectiveSetting)(nil),            // 22: openshell.sandbox.v1.EffectiveSetting
	(*GetSandboxConfigResponse)(nil),    // 23: openshell.sandbox.v1.GetSandboxConfigResponse
	(*SupervisorMiddlewareService)(nil), // 24: openshell.sandbox.v1.SupervisorMiddlewareService
	nil,                                 // 25: openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntry
	nil,                                 // 26: openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntry
	nil,                                 // 27: openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	nil,                                 // 28: openshell.sandbox.v1.L7DenyRule.QueryEntry
	nil,                                 // 29: openshell.sandbox.v1.L7DenyRule.ParamsEntry
	nil,                                 // 30: openshell.sandbox.v1.L7Allow.QueryEntry
	nil,                                 // 31: openshell.sandbox.v1.L7Allow.ParamsEntry
	nil,                                 // 32: openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntry
	nil,                                 // 33: openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntry
	(*structpb.Struct)(nil),             // 34: google.protobuf.Struct
}
var file_sandbox_proto_depIdxs = []int32{
	3,  // 0: openshell.sandbox.v1.SandboxPolicy.filesystem:type_name -> openshell.sandbox.v1.FilesystemPolicy
	4,  // 1: openshell.sandbox.v1.SandboxPolicy.landlock:type_name -> openshell.sandbox.v1.LandlockPolicy
	5,  // 2: openshell.sandbox.v1.SandboxPolicy.process:type_name -> openshell.sandbox.v1.ProcessPolicy
	25, // 3: openshell.sandbox.v1.SandboxPolicy.network_policies:type_name -> openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntry
	26, // 4: openshell.sandbox.v1.SandboxPolicy.network_middlewares:type_name -> openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntry
	10, // 5: openshell.sandbox.v1.NetworkPolicyRule.endpoints:type_name -> openshell.sandbox.v1.NetworkEndpoint
	17, // 6: openshell.sandbox.v1.NetworkPolicyRule.binaries:type_name -> openshell.sandbox.v1.NetworkBinary
	34, // 7: openshell.sandbox.v1.NetworkMiddlewareConfig.config:type_name -> google.protobuf.Struct
	8,  // 8: openshell.sandbox.v1.NetworkMiddlewareConfig.endpoints:type_name -> openshell.sandbox.v1.MiddlewareEndpointSelector
	14, // 9: openshell.sandbox.v1.NetworkEndpoint.rules:type_name -> openshell.sandbox.v1.L7Rule
	13, // 10: openshell.sandbox.v1.NetworkEndpoint.deny_rules:type_name -> openshell.sandbox.v1.L7DenyRule
	27, // 11: openshell.sandbox.v1.NetworkEndpoint.graphql_persisted_queries:type_name -> openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	11, // 12: openshell.sandbox.v1.NetworkEndpoint.mcp:type_name -> openshell.sandbox.v1.McpOptions
	9,  // 13: openshell.sandbox.v1.NetworkEndpoint.credential_binding:type_name -> openshell.sandbox.v1.NetworkCredentialBinding
	28, // 14: openshell.sandbox.v1.L7DenyRule.query:type_name -> openshell.sandbox.v1.L7DenyRule.QueryEntry
	29, // 15: openshell.sandbox.v1.L7DenyRule.params:type_name -> openshell.sandbox.v1.L7DenyRule.ParamsEntry
	15, // 16: openshell.sandbox.v1.L7Rule.allow:type_name -> openshell.sandbox.v1.L7Allow
	30, // 17: openshell.sandbox.v1.L7Allow.query:type_name -> openshell.sandbox.v1.L7Allow.QueryEntry
	31, // 18: openshell.sandbox.v1.L7Allow.params:type_name -> openshell.sandbox.v1.L7Allow.ParamsEntry
	32, // 19: openshell.sandbox.v1.GetGatewayConfigResponse.settings:type_name -> openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntry
	21, // 20: openshell.sandbox.v1.EffectiveSetting.value:type_name -> openshell.sandbox.v1.SettingValue
	0,  // 21: openshell.sandbox.v1.EffectiveSetting.scope:type_name -> openshell.sandbox.v1.SettingScope
	2,  // 22: openshell.sandbox.v1.GetSandboxConfigResponse.policy:type_name -> openshell.sandbox.v1.SandboxPolicy
	33, // 23: openshell.sandbox.v1.GetSandboxConfigResponse.settings:type_name -> openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntry
	1,  // 24: openshell.sandbox.v1.GetSandboxConfigResponse.policy_source:type_name -> openshell.sandbox.v1.PolicySource
	24, // 25: openshell.sandbox.v1.GetSandboxConfigResponse.supervisor_middleware_services:type_name -> openshell.sandbox.v1.SupervisorMiddlewareService
	6,  // 26: openshell.sandbox.v1.SandboxPolicy.NetworkPoliciesEntry.value:type_name -> openshell.sandbox.v1.NetworkPolicyRule
	7,  // 27: openshell.sandbox.v1.SandboxPolicy.NetworkMiddlewaresEntry.value:type_name -> openshell.sandbox.v1.NetworkMiddlewareConfig
	12, // 28: openshell.sandbox.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry.value:type_name -> openshell.sandbox.v1.GraphqlOperation
	16, // 29: openshell.sandbox.v1.L7DenyRule.QueryEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	16, // 30: openshell.sandbox.v1.L7DenyRule.ParamsEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	16, // 31: openshell.sandbox.v1.L7Allow.QueryEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	16, // 32: openshell.sandbox.v1.L7Allow.ParamsEntry.value:type_name -> openshell.sandbox.v1.L7QueryMatcher
	21, // 33: openshell.sandbox.v1.GetGatewayConfigResponse.SettingsEntry.value:type_name -> openshell.sandbox.v1.SettingValue
	22, // 34: openshell.sandbox.v1.GetSandboxConfigResponse.SettingsEntry.value:type_name -> openshell.sandbox.v1.EffectiveSetting
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	file_sandbox_proto_msgTypes[9].OneofWrappers = []any{}
	file_sandbox_proto_msgTypes[19].OneofWrappers = []any{
		(*SettingValue_StringValue)(nil),
		(*SettingValue_BoolValue)(nil),
		(*SettingValue_IntValue)(nil),
		(*SettingValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		EnumInfos:         file_sandbox_proto_enumTypes,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
