// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Exact configuration and runtime identities used by admission and activation.

use serde::{Deserialize, Serialize};

/// Immutable identity of a complete policy and provider candidate.
///
/// Equality includes provider and configuration revisions even when policy
/// content is unchanged. A matching policy hash alone cannot acknowledge an
/// independently refreshed credential environment.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigurationRevision {
    /// Gateway revision of the complete effective configuration.
    pub config_revision: u64,
    /// Version of the selected policy within its source.
    pub policy_version: u32,
    /// Hash of the selected effective policy.
    pub policy_hash: String,
    /// Numeric value of the gateway `PolicySource` enum.
    pub policy_source: i32,
    /// Revision of the exact prepared provider environment.
    pub provider_env_revision: u64,
}

impl ConfigurationRevision {
    /// Reject revision identities that cannot name a selected configuration.
    ///
    /// # Errors
    /// Returns an error for an absent configuration revision, empty or
    /// whitespace-bearing hash, or unspecified/unknown policy source.
    pub fn validate(&self) -> Result<(), ConfigurationIdentityError> {
        if self.config_revision == 0 {
            return Err(ConfigurationIdentityError::Invalid(
                "configuration revision",
            ));
        }
        if self.policy_hash.is_empty()
            || self.policy_hash.len() > 128
            || self.policy_hash.chars().any(char::is_whitespace)
        {
            return Err(ConfigurationIdentityError::Invalid("policy hash"));
        }
        if !matches!(
            crate::proto::PolicySource::try_from(self.policy_source),
            Ok(source) if source != crate::proto::PolicySource::Unspecified
        ) {
            return Err(ConfigurationIdentityError::Invalid("policy source"));
        }
        Ok(())
    }
}

/// Current registered control process and exact workload boundary incarnation.
///
/// A driver runtime generation survives control transport reconnects. A fresh
/// boundary process has a different incarnation even if the outer resource
/// accidentally retains the same runtime descriptor.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigurationActivationIdentity {
    /// Driver-owned runtime generation.
    pub runtime_generation: String,
    /// Gateway-issued launch session UUID.
    pub boundary_session_id: String,
    /// One process UUID shared by admission, boundary control, and readiness.
    pub supervisor_instance_id: String,
    /// Fresh UUID generated by the boundary process.
    pub boundary_instance_id: String,
    /// Gateway-signed registration fence; zero only during bootstrap discovery.
    pub registration_revision: u64,
}

impl ConfigurationActivationIdentity {
    /// Validate immutable runtime and process coordinates from bootstrap.
    ///
    /// # Errors
    /// Returns an error for malformed runtime or noncanonical/nil UUIDs.
    pub fn validate_bootstrap(&self) -> Result<(), ConfigurationIdentityError> {
        if self.runtime_generation.is_empty()
            || self.runtime_generation.len() > 256
            || self.runtime_generation.chars().any(char::is_whitespace)
        {
            return Err(ConfigurationIdentityError::Invalid("runtime generation"));
        }
        for (field, value) in [
            ("boundary session ID", &self.boundary_session_id),
            ("supervisor instance ID", &self.supervisor_instance_id),
            ("boundary instance ID", &self.boundary_instance_id),
        ] {
            let id = uuid::Uuid::parse_str(value)
                .map_err(|_| ConfigurationIdentityError::Invalid(field))?;
            if id.is_nil() || id.hyphenated().to_string() != *value {
                return Err(ConfigurationIdentityError::Invalid(field));
            }
        }
        Ok(())
    }

    /// Require a complete runtime identity and an issued registration fence.
    ///
    /// # Errors
    /// Returns an error for malformed coordinates or an unregistered identity.
    pub fn validate(&self) -> Result<(), ConfigurationIdentityError> {
        self.validate_bootstrap()?;
        if self.registration_revision == 0 {
            return Err(ConfigurationIdentityError::Invalid("registration revision"));
        }
        Ok(())
    }

    /// Compare immutable runtime/process coordinates before registration is issued.
    #[must_use]
    pub fn same_incarnation(&self, other: &Self) -> bool {
        self.runtime_generation == other.runtime_generation
            && self.boundary_session_id == other.boundary_session_id
            && self.supervisor_instance_id == other.supervisor_instance_id
            && self.boundary_instance_id == other.boundary_instance_id
    }
}

/// Invalid field in an admission or activation identity.
///
/// Only the field name is reported; raw candidate policy and credentials must
/// not appear in identity diagnostics.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
pub enum ConfigurationIdentityError {
    /// A required coordinate is missing, malformed, or unspecified.
    #[error("invalid configuration identity field: {0}")]
    Invalid(&'static str),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn identity() -> ConfigurationActivationIdentity {
        ConfigurationActivationIdentity {
            runtime_generation: "runtime-1".to_string(),
            boundary_session_id: "11111111-1111-4111-8111-111111111111".to_string(),
            supervisor_instance_id: "22222222-2222-4222-8222-222222222222".to_string(),
            boundary_instance_id: "33333333-3333-4333-8333-333333333333".to_string(),
            registration_revision: 1,
        }
    }

    #[test]
    fn configuration_activation_requires_registered_canonical_process_identity() {
        let valid = identity();
        assert_eq!(valid.validate(), Ok(()));
        let mut candidate = valid.clone();
        candidate.registration_revision = 0;
        assert_eq!(candidate.validate_bootstrap(), Ok(()));
        assert!(candidate.validate().is_err());
        candidate = valid.clone();
        candidate.boundary_instance_id = uuid::Uuid::nil().to_string();
        assert!(candidate.validate_bootstrap().is_err());
        candidate = valid;
        candidate.supervisor_instance_id = "not-a-process-identity".to_string();
        assert!(candidate.validate_bootstrap().is_err());
    }

    #[test]
    fn configuration_activation_equality_fences_registration_and_boundary_restart() {
        let original = identity();
        let mut replacement = original.clone();
        replacement.registration_revision += 1;
        assert!(original.same_incarnation(&replacement));
        assert_ne!(original, replacement);
        replacement.boundary_instance_id = "44444444-4444-4444-8444-444444444444".to_string();
        assert!(!original.same_incarnation(&replacement));
    }

    #[test]
    fn configuration_activation_revision_rejects_unnamed_or_unknown_policy() {
        let valid = ConfigurationRevision {
            config_revision: 1,
            policy_version: 0,
            policy_hash: "global-policy".to_string(),
            policy_source: crate::proto::PolicySource::Global.into(),
            provider_env_revision: 0,
        };
        assert_eq!(
            valid.validate(),
            Ok(()),
            "global policy and absent providers may have zero subordinate revisions"
        );
        for field in [
            "configuration",
            "hash",
            "whitespace",
            "source",
            "unknown_source",
        ] {
            let mut candidate = valid.clone();
            match field {
                "configuration" => candidate.config_revision = 0,
                "hash" => candidate.policy_hash.clear(),
                "whitespace" => candidate.policy_hash = "ambiguous hash".to_string(),
                "source" => candidate.policy_source = 0,
                "unknown_source" => candidate.policy_source = i32::MAX,
                _ => unreachable!("fixed revision fixture"),
            }
            assert!(
                candidate.validate().is_err(),
                "invalid {field} must be rejected"
            );
        }
    }
}
