# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: RPM Package

on:
  workflow_call:
    inputs:
      checkout-ref:
        required: true
        type: string
      rpm-version:
        required: false
        type: string
        default: ""
      rpm-release:
        required: false
        type: string
        default: ""
      cargo-version:
        required: false
        type: string
        default: ""

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build-rpm-linux:
    name: Build RPM Package (Linux ${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: linux-amd64-cpu8
            cli_target: x86_64-unknown-linux-musl
            gateway_target: x86_64-unknown-linux-gnu
            prover_target: x86_64-unknown-linux-musl
          - arch: aarch64
            runner: linux-arm64-cpu8
            cli_target: aarch64-unknown-linux-musl
            gateway_target: aarch64-unknown-linux-gnu
            prover_target: aarch64-unknown-linux-musl
    uses: ./.github/workflows/build-rpm.yml
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.runner }}
      cli-target: ${{ matrix.cli_target }}
      gateway-target: ${{ matrix.gateway_target }}
      prover-target: ${{ matrix.prover_target }}
      rpm-version: ${{ inputs.rpm-version }}
      rpm-release: ${{ inputs.rpm-release }}
      cargo-version: ${{ inputs.cargo-version }}
